apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi
  namespace: unifi1
spec:
  project: internal
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - chart: unifi
    repoURL: https://github.com/Rajsharan123/k3s-unifi/templates/
    #targetRevision: 4.10.1
    helm:
      valueFiles:
      - $values/configs/internal/unifi/values.yaml
  - repoURL: https://github.com/Rajsharan123/k3s-unifi.git
    targetRevision: main
    ref: values
  destination:
    name: in-cluster
    namespace: unifi1
